---
- name: Unison Deployment Playbook
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  environment:
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default('ap-southeast-2', true) }}"
  tasks:
    - include: tasks/app_deploy.yml