---
- name: Install Apache web server
  yum: name={{ item }} state=present
  with_items:
    - httpd

- name: Install git
  yum: name={{ item }} state=installed
  with_items:
    - git

- name: ensure apache is running
  service: name=httpd state=started enabled=yes

- name: Deploy the code from repository
  git: repo={{ apprepository }} dest=/var/www/html/